title: GeoDMS
description: GeoDms documentation
theme: just-the-docs

url: https://just-the-docs.github.io
math: mathjax
color_scheme: wider
back_to_top: true
back_to_top_text: "Back to top"
#logo: "/assets/img/GeoDmsGuiQt.png"

aux_links:
  GeoDms on Github: https://github.com/ObjectVision/GeoDMS

nav_external_links:
  - title: Releases
    url: https://github.com/ObjectVision/GeoDMS/releases
    hide_icon: false # set to true to hide the external link icon
    opens_in_new_tab: true # set to true to open this link in a new tab
    parent: Software