title: GeoDMS wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io
math: mathjax
color_scheme: wider
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  GeoDms on Github: https://github.com/ObjectVision/GeoDMS
